---
- name: Update and upgrade CentOS servers
  hosts: all
  gather_facts: false

  tasks:
    - name: Update package cache
      become: yes
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Upgrade packages
      become: yes
      yum:
        name: '*'
        state: latest
